"""initial

Revision ID: 02308bb56429
Revises: 27aeea4b2d95
Create Date: 2025-06-30 21:35:30.206881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02308bb56429'
down_revision = '27aeea4b2d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
