"""rename nama_posisi to nama_pekerjaan

Revision ID: 27aeea4b2d95
Revises: d996373279f4
Create Date: 2025-06-24 21:07:40.408730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27aeea4b2d95'
down_revision = 'd996373279f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_pekerjaan', sa.Text(), nullable=True))
        batch_op.drop_column('nama_posisi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_posisi', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('nama_pekerjaan')

    # ### end Alembic commands ###
