"""initial

Revision ID: 84cdd7c31408
Revises: 02308bb56429
Create Date: 2025-07-12 12:26:10.306417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cdd7c31408'
down_revision = '02308bb56429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gaji', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipe_pekerjaan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tanggal_ditutup', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('syarat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefit', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link_apply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nama_pekerjaan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('perusahaan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('lokasi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('prodi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('jurusan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('jurusan',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('prodi',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nama',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.alter_column('lokasi',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('perusahaan',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nama_pekerjaan',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('link_apply')
        batch_op.drop_column('benefit')
        batch_op.drop_column('syarat')
        batch_op.drop_column('tanggal_ditutup')
        batch_op.drop_column('tipe_pekerjaan')
        batch_op.drop_column('gaji')

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
