"""inisialisasi database

Revision ID: d996373279f4
Revises: 
Create Date: 2025-06-21 21:36:48.086508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd996373279f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_rekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pekerjaan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pekerjaan_id'], ['pekerjaan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recommendations')
    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_posisi', sa.Text(), nullable=True))
        batch_op.alter_column('perusahaan',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('lokasi',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('rekomendasi_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('posisi')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pekerjaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('posisi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('rekomendasi_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('lokasi',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('perusahaan',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('nama_posisi')

    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pekerjaan_direkomendasikan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recommendations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )
    op.drop_table('hasil_rekomendasi')
    # ### end Alembic commands ###
